# Generated by Django 4.0.5 on 2022-06-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prac', '0002_user_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userName',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
